apiVersion: batch/v1
kind: Job
metadata:
  name: crawl
spec:
  completions: 1
  template:
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: casper-worker-key
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-vol
      containers:
      - name: crawl
        image:  hemanthk0208/spider:v1
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.05"
          limits:
            memory: "120Mi"
            cpu: "0.09"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: my-volume
          mountPath: /home/git/
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["scrapy", "runspider", "/home/git/app/code/crawl.py"]
      restartPolicy: OnFailure
  backoffLimit: 4
