apiVersion: batch/v1
kind: Job
metadata:
  name: spider
spec:
  parallelism: 8
  template:
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: casper-worker-key
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-vol
      containers:
      - name: spider
        image:  hemanthk0208/spider:v1
        resources:
          requests:
            memory: "150Mi"
            cpu: "0.1"
          limits:
            memory: "180Mi"
            cpu: "0.12"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: my-volume
          mountPath: /home/git/
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["scrapy", "runspider", "/home/git/app/code/spider.py"]
      restartPolicy: OnFailure
  backoffLimit: 3
